Resolve failure when running tests locally
Running the test suite locally fails with the following error:

File "/Users/markwhitaker/Workspaces/laa-fee-calculator/fee_calculator/apps/calculator/tests/__init__.py", line 28, in run_tests
    self.run_checks(['default'])
TypeError: DiscoverRunner.run_checks() takes 1 positional argument but 2 were given

The '[default]' argument was introduced in
https://github.com/ministryofjustice/laa-fee-calculator/commit/c35e4dbde3cd4df21455b42cc4cea7ec41dd1481
but seems to be breaking local test runs. This reverts the change.