Bump Django Django>=2.2,<2.3 to Django>=3.2,<4.1
Required:

1. explicit naming of default database for tests, to fix:

  ```sh
    File "/root/project/fee_calculator/apps/calculator/tests/__init__.py", line 28, in run_tests
      self.run_checks()
  TypeError: run_checks() missing 1 required positional argument: 'databases'
  ```

2. Add DEFAULT_AUTO_FIELD, to fix warnings

  Examplewarning
  ```sh
  calculator.Scenario: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
    HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'
  ```
  see https://docs.djangoproject.com/en/4.0/releases/3.2/#customizing-type-of-auto-created-primary-keys