Fix for bump to django 3.1+
Fixes below error when running tests:

```
  File "/root/project/fee_calculator/apps/calculator/tests/__init__.py", line 28, in run_tests
    self.run_checks()
TypeError: run_checks() missing 1 required positional argument: 'databases'
```